### ISSUE TITLE
Filtering example

### ISSUE THREAD

**Issue by egils-consulting** [ebraminio/aiosseclient#5]
Thabks a lot for writing and sharing this ❤
I just build a small script/bot using this and mediawikiapi.
I have a suggestion to expand he readme with a filtering example, woukd that be accepted?

**Comment by ebraminio** [comment]
Oh. Sure!

**Comment by egils-consulting** [comment]
I'll try to put together a pull requests for the readme then 😃

**Comment by ebraminio** [comment]
Sounds great. Thanks :)
