### ISSUE TITLE
Publish to pip?

### ISSUE THREAD

**Issue by dpriskorn** [ebraminio/aiosseclient#8]
I use this in https://github.com/dpriskorn/asseeibot and would like to fetch it from PIP if possible.

**Comment by ebraminio** [comment]
Done https://pypi.org/project/aiosseclient/0.0.1/ :)

**Comment by ebraminio** [comment]
And sorry for the late response as this was my first experience with, hopefully everything works smoothly there, if not feel free to ping and I will try to resolve immediately. Thanks :)
